# MySQL Connection
spring.datasource.url=jdbc:mysql://localhost:3306/resume_ats_db
spring.datasource.username=root
spring.datasource.password=Bunny@2003

# Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Allow large file uploads for resumes
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

# Adzuna API Keys (Replace with your real keys later)
adzuna.app.id=79eeb71b
adzuna.app.key=3d763a0c66495c6c0d3ab7ebb8fd3787
server.port=8081
